
CREATE TABLE BLOQUEOS_LOGIN 
   (	ID bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL , 
	CLAVE varchar(255)  NOT NULL , 
	TIPO varchar(20)  NOT NULL , 
	FALLOS numeric DEFAULT 0 NOT NULL , 
	NIVEL numeric DEFAULT 0 NOT NULL , 
	BLOQUEO_HASTA timestamptz, 
	CREADO_EN timestamptz DEFAULT now(), 
	ACTUALIZADO_EN timestamptz DEFAULT now(), 
	 PRIMARY KEY (ID)
   );

CREATE UNIQUE INDEX IF NOT EXISTS bloqueos_login_clave_tipo_uq ON bloqueos_login (lower(clave), tipo);
