-- CODIGOS_RESPALDO: generado desde el DDL de Oracle (DBMS_METADATA.GET_DDL).
-- No editar a mano: regenerar con tools/migrar_ddl_oracle.py.

CREATE TABLE CODIGOS_RESPALDO 
   (	ID bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL , 
	USER_ID varchar(36)  NOT NULL , 
	CODIGO_HASH varchar(255)  NOT NULL , 
	USADO boolean DEFAULT false NOT NULL , 
	CREADO_EN timestamptz DEFAULT now(), 
	 PRIMARY KEY (ID)
    
   
    
   );
