-- LOGS_SEGURIDAD: generado desde el DDL de Oracle (DBMS_METADATA.GET_DDL).
-- No editar a mano: regenerar con tools/migrar_ddl_oracle.py.

CREATE TABLE LOGS_SEGURIDAD 
   (	ID bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL , 
	EVENTO varchar(50)  NOT NULL , 
	USER_ID varchar(36) , 
	IP varchar(45) , 
	DETALLE varchar(500) , 
	CREADO_EN timestamptz DEFAULT now(), 
	 PRIMARY KEY (ID)
    
   
    
   );
