-- Schema Postgres de ApoloVibes, generado desde el DDL de Oracle APOLODEV.
-- Ordenado por dependencias de FK. Regenerar con tools/migrar_ddl_oracle.py.

-- ---- BLOQUEOS_LOGIN
CREATE TABLE BLOQUEOS_LOGIN 
   (	ID bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL , 
	CLAVE varchar(255)  NOT NULL , 
	TIPO varchar(20)  NOT NULL , 
	FALLOS numeric DEFAULT 0 NOT NULL , 
	NIVEL numeric DEFAULT 0 NOT NULL , 
	BLOQUEO_HASTA timestamptz, 
	CREADO_EN timestamptz DEFAULT now(), 
	ACTUALIZADO_EN timestamptz DEFAULT now(), 
	 PRIMARY KEY (ID)
    
   
    
   );

-- ---- CATEGORIAS
CREATE TABLE CATEGORIAS 
   (	ID uuid DEFAULT gen_random_uuid(), 
	NOMBRE varchar(100)  NOT NULL , 
	DESCRIPCION text , 
	 PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT UQ_CATEGORIAS_NOMBRE UNIQUE (NOMBRE)
    
   
    
   );

-- ---- CODIGOS_RESPALDO
CREATE TABLE CODIGOS_RESPALDO 
   (	ID bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL , 
	USER_ID varchar(36)  NOT NULL , 
	CODIGO_HASH varchar(255)  NOT NULL , 
	USADO boolean DEFAULT false NOT NULL , 
	CREADO_EN timestamptz DEFAULT now(), 
	 PRIMARY KEY (ID)
    
   
    
   );

-- ---- CODIGOS_VERIFICACION
CREATE TABLE CODIGOS_VERIFICACION 
   (	EMAIL varchar(255)  NOT NULL , 
	CODIGO_HASH varchar(255)  NOT NULL , 
	EXPIRA_EN timestamptz NOT NULL , 
	USADO boolean DEFAULT false NOT NULL , 
	CREADO_EN timestamptz DEFAULT now()
   );

-- ---- LOGS_SEGURIDAD
CREATE TABLE LOGS_SEGURIDAD 
   (	ID bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL , 
	EVENTO varchar(50)  NOT NULL , 
	USER_ID varchar(36) , 
	IP varchar(45) , 
	DETALLE varchar(500) , 
	CREADO_EN timestamptz DEFAULT now(), 
	 PRIMARY KEY (ID)
    
   
    
   );

-- ---- REFRESH_TOKENS
CREATE TABLE REFRESH_TOKENS 
   (	JTI varchar(36) , 
	USER_ID varchar(36)  NOT NULL , 
	EXPIRA_EN timestamptz NOT NULL , 
	REVOCADO boolean DEFAULT false NOT NULL , 
	IP varchar(45) , 
	USER_AGENT varchar(255) , 
	CREADO_EN timestamptz DEFAULT now(), 
	 PRIMARY KEY (JTI)
    
   
    
   );

-- ---- USUARIOS
CREATE TABLE USUARIOS 
   (	ID uuid DEFAULT gen_random_uuid(), 
	EMAIL varchar(255)  NOT NULL , 
	PASSWORD_HASH varchar(255)  NOT NULL , 
	NOMBRE varchar(100)  NOT NULL , 
	APELLIDO varchar(100) , 
	TELEFONO varchar(30) , 
	ROL varchar(20)  DEFAULT 'cliente' NOT NULL , 
	ACTIVO boolean DEFAULT true NOT NULL , 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	AUTH_PROVIDER varchar(20)  DEFAULT 'local' NOT NULL , 
	GOOGLE_SUB varchar(255) , 
	MFA_SECRET varchar(64) , 
	MFA_ACTIVO boolean DEFAULT false NOT NULL , 
	 CHECK (rol IN ('admin', 'cliente')) , 
	 CONSTRAINT CK_USUARIOS_APELLIDO CHECK (rol <> 'cliente' OR apellido IS NOT NULL) , 
	 PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT UQ_USUARIOS_EMAIL UNIQUE (EMAIL)
    
   
    
   );

-- ---- CARRITO
CREATE TABLE CARRITO 
   (	ID uuid DEFAULT gen_random_uuid(), 
	USUARIO_ID uuid NOT NULL , 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	ACTUALIZADO_EN timestamptz DEFAULT now() NOT NULL , 
	 PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT UQ_CARRITO_USUARIO UNIQUE (USUARIO_ID)
    
   
    , 
	 CONSTRAINT FK_CARRITO_USUARIO FOREIGN KEY (USUARIO_ID)
	  REFERENCES USUARIOS (ID) 
   );

-- ---- LOGS_AUDITORIA
CREATE TABLE LOGS_AUDITORIA 
   (	ID uuid DEFAULT gen_random_uuid(), 
	USUARIO_ID uuid, 
	ACCION varchar(100)  NOT NULL , 
	ENTIDAD_TIPO varchar(50)  NOT NULL , 
	ENTIDAD_ID varchar(50) , 
	DETALLE text , 
	IP varchar(45) , 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	 PRIMARY KEY (ID)
   , 
	 CONSTRAINT FK_LOG_USUARIO FOREIGN KEY (USUARIO_ID)
	  REFERENCES USUARIOS (ID) 
   );

-- ---- NOTIFICACIONES
CREATE TABLE NOTIFICACIONES 
   (	ID uuid DEFAULT gen_random_uuid(), 
	USUARIO_ID uuid NOT NULL , 
	TIPO varchar(50)  NOT NULL , 
	CANAL varchar(20)  DEFAULT 'email' NOT NULL , 
	ASUNTO varchar(255) , 
	CONTENIDO text , 
	LEIDA boolean DEFAULT false NOT NULL , 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	 CHECK (canal IN ('email', 'sms', 'push')) , 
	 PRIMARY KEY (ID)
   , 
	 CONSTRAINT FK_NOTIF_USUARIO FOREIGN KEY (USUARIO_ID)
	  REFERENCES USUARIOS (ID) 
   );

-- ---- PEDIDOS
CREATE TABLE PEDIDOS 
   (	ID uuid DEFAULT gen_random_uuid(), 
	USUARIO_ID uuid NOT NULL , 
	ESTADO varchar(30)  DEFAULT 'pendiente' NOT NULL , 
	TOTAL numeric(10,2) DEFAULT 0 NOT NULL , 
	DIRECCION_ENVIO text , 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	CODIGO_SEGUIMIENTO varchar(50) , 
	ESTADO_SEGUIMIENTO varchar(100) , 
	SEGUIMIENTO_ACTUALIZADO_EN timestamptz, 
	 CHECK (estado IN (
                        'pendiente', 'en_produccion', 'enviado',
                        'entregado', 'cancelado'
                    )) , 
	 CHECK (total >= 0) , 
	 PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (USUARIO_ID)
	  REFERENCES USUARIOS (ID) 
   );

-- ---- PRODUCTOS
CREATE TABLE PRODUCTOS 
   (	ID uuid DEFAULT gen_random_uuid(), 
	CATEGORIA_ID uuid NOT NULL , 
	NOMBRE varchar(150)  NOT NULL , 
	DESCRIPCION text , 
	PRECIO numeric(10,2) NOT NULL , 
	STOCK numeric DEFAULT 0 NOT NULL , 
	IMAGEN varchar(500) , 
	ACTIVO boolean DEFAULT true NOT NULL , 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	IMAGEN_BYTES bytea, 
	IMAGEN_CONTENT_TYPE varchar(50) , 
	SPECS text , 
	DESCUENTO numeric, 
	BADGE varchar(50) , 
	PRECIO_ORIGINAL numeric, 
	RATING numeric, 
	MATERIAL varchar(100) , 
	TAMANO varchar(100) , 
	COLOR varchar(100) , 
	IMAGEN_THUMB_BYTES bytea, 
	IMAGEN_THUMB_CONTENT_TYPE varchar(50) , 
	NUEVO_LANZAMIENTO boolean DEFAULT false NOT NULL , 
	 CHECK (precio >= 0) , 
	 CHECK (stock >= 0) , 
	 PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID)
	  REFERENCES CATEGORIAS (ID) 
   );

-- ---- SESIONES_VENTA
CREATE TABLE SESIONES_VENTA 
   (	ID uuid NOT NULL , 
	LUGAR varchar(150)  NOT NULL , 
	FECHA date NOT NULL , 
	ESTADO varchar(20)  NOT NULL , 
	USUARIO_ID uuid NOT NULL , 
	CREADO_EN timestamptz NOT NULL , 
	CERRADA_EN timestamptz, 
	 CONSTRAINT PK_SESIONES_VENTA PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_SESIONES_VENTA_USUARIO FOREIGN KEY (USUARIO_ID)
	  REFERENCES USUARIOS (ID) 
   );

-- ---- SOLICITUDES_DISENO
CREATE TABLE SOLICITUDES_DISENO 
   (	ID uuid DEFAULT gen_random_uuid(), 
	USUARIO_ID uuid NOT NULL , 
	NOMBRE varchar(150)  NOT NULL , 
	EMAIL varchar(255)  NOT NULL , 
	TELEFONO varchar(30) , 
	MATERIAL varchar(30)  NOT NULL , 
	DESCRIPCION text  NOT NULL , 
	ESTADO varchar(30)  DEFAULT 'pendiente' NOT NULL , 
	IMAGEN varchar(500) , 
	MODELO_URL varchar(500) , 
	PRECIO numeric(10,2), 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	 CHECK (material IN ('PLA', 'PETG', 'Resina', 'ABS')) , 
	 CHECK (estado IN ('pendiente', 'aprobada', 'rechazada')) , 
	 CHECK (precio >= 0) , 
	 PRIMARY KEY (ID)
   , 
	 CONSTRAINT FK_SOLICITUD_USUARIO FOREIGN KEY (USUARIO_ID)
	  REFERENCES USUARIOS (ID) 
   );

-- ---- CARRITO_ITEMS
CREATE TABLE CARRITO_ITEMS 
   (	ID uuid DEFAULT gen_random_uuid(), 
	CARRITO_ID uuid NOT NULL , 
	PRODUCTO_ID uuid NOT NULL , 
	CANTIDAD numeric DEFAULT 1 NOT NULL , 
	AGREGADO_EN timestamptz DEFAULT now() NOT NULL , 
	COLOR varchar(50) , 
	 CHECK (cantidad > 0) , 
	 PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_CARRITO_ITEM_CARRITO FOREIGN KEY (CARRITO_ID)
	  REFERENCES CARRITO (ID) , 
	 CONSTRAINT FK_CARRITO_ITEM_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
	  REFERENCES PRODUCTOS (ID) 
   );

-- ---- DETALLE_PEDIDOS
CREATE TABLE DETALLE_PEDIDOS 
   (	ID uuid DEFAULT gen_random_uuid(), 
	PEDIDO_ID uuid NOT NULL , 
	PRODUCTO_ID uuid NOT NULL , 
	CANTIDAD numeric NOT NULL , 
	PRECIO_UNITARIO numeric(10,2) NOT NULL , 
	COLOR varchar(50) , 
	 CHECK (cantidad > 0) , 
	 CHECK (precio_unitario >= 0) , 
	 PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_DETALLE_PEDIDO FOREIGN KEY (PEDIDO_ID)
	  REFERENCES PEDIDOS (ID) , 
	 CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
	  REFERENCES PRODUCTOS (ID) 
   );

-- ---- PAGOS
CREATE TABLE PAGOS 
   (	ID uuid DEFAULT gen_random_uuid(), 
	PEDIDO_ID uuid NOT NULL , 
	MONTO numeric(10,2) NOT NULL , 
	PROVEEDOR varchar(50)  NOT NULL , 
	TOKEN varchar(255) , 
	ESTADO varchar(30)  DEFAULT 'pendiente' NOT NULL , 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	 CHECK (monto >= 0) , 
	 CHECK (estado IN (
                   'pendiente', 'autorizado', 'completado',
                   'fallido', 'reembolsado'
               )) , 
	 PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_PAGO_PEDIDO FOREIGN KEY (PEDIDO_ID)
	  REFERENCES PEDIDOS (ID) 
   );

-- ---- PRODUCTO_COLORES
CREATE TABLE PRODUCTO_COLORES 
   (	ID uuid NOT NULL , 
	PRODUCTO_ID uuid NOT NULL , 
	NOMBRE varchar(50)  NOT NULL , 
	IMAGEN_BYTES bytea, 
	IMAGEN_CONTENT_TYPE varchar(50) , 
	ORDEN integer DEFAULT 0 NOT NULL , 
	CREADO_EN timestamptz DEFAULT now() NOT NULL , 
	IMAGEN_THUMB_BYTES bytea, 
	IMAGEN_THUMB_CONTENT_TYPE varchar(50) , 
	 CONSTRAINT PK_PRODUCTO_COLORES PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_PRODUCTO_COLORES_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
	  REFERENCES PRODUCTOS (ID) 
   );

-- ---- VENTAS_LOCAL
CREATE TABLE VENTAS_LOCAL 
   (	ID uuid NOT NULL , 
	SESION_ID uuid NOT NULL , 
	MEDIO_PAGO varchar(20)  NOT NULL , 
	TOTAL bigint NOT NULL , 
	CREADO_EN timestamptz NOT NULL , 
	 CONSTRAINT PK_VENTAS_LOCAL PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_VENTAS_LOCAL_SESION FOREIGN KEY (SESION_ID)
	  REFERENCES SESIONES_VENTA (ID) 
   );

-- ---- VENTA_LOCAL_ITEMS
CREATE TABLE VENTA_LOCAL_ITEMS 
   (	ID uuid NOT NULL , 
	VENTA_ID uuid NOT NULL , 
	PRODUCTO_ID uuid NOT NULL , 
	NOMBRE varchar(200)  NOT NULL , 
	CANTIDAD bigint NOT NULL , 
	PRECIO_UNITARIO bigint NOT NULL , 
	 CONSTRAINT PK_VENTA_LOCAL_ITEMS PRIMARY KEY (ID)
    
   
    , 
	 CONSTRAINT FK_ITEMS_VENTA FOREIGN KEY (VENTA_ID)
	  REFERENCES VENTAS_LOCAL (ID) , 
	 CONSTRAINT FK_ITEMS_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
	  REFERENCES PRODUCTOS (ID) 
   );

-- ---- Indices
CREATE UNIQUE INDEX IF NOT EXISTS bloqueos_login_clave_tipo_uq ON bloqueos_login (lower(clave), tipo);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios (rol);
CREATE INDEX IF NOT EXISTS idx_log_creado ON logs_auditoria (creado_en);
CREATE INDEX IF NOT EXISTS idx_log_entidad ON logs_auditoria (entidad_tipo, entidad_id);
CREATE INDEX IF NOT EXISTS idx_log_usuario ON logs_auditoria (usuario_id);
CREATE INDEX IF NOT EXISTS idx_notif_leida ON notificaciones (leida);
CREATE INDEX IF NOT EXISTS idx_notif_usuario ON notificaciones (usuario_id);
CREATE INDEX IF NOT EXISTS idx_pedido_creado ON pedidos (creado_en);
CREATE INDEX IF NOT EXISTS idx_pedido_estado ON pedidos (estado);
CREATE INDEX IF NOT EXISTS idx_pedido_usuario ON pedidos (usuario_id);
CREATE INDEX IF NOT EXISTS idx_producto_activo ON productos (activo);
CREATE INDEX IF NOT EXISTS idx_producto_categoria ON productos (categoria_id);
CREATE INDEX IF NOT EXISTS ix_sesiones_venta_usuario ON sesiones_venta (usuario_id);
CREATE UNIQUE INDEX IF NOT EXISTS pk_sesiones_venta ON sesiones_venta (id);
CREATE INDEX IF NOT EXISTS idx_solicitud_estado ON solicitudes_diseno (estado);
CREATE INDEX IF NOT EXISTS idx_solicitud_usuario ON solicitudes_diseno (usuario_id);
ALTER TABLE carrito_items ADD CONSTRAINT ck_carrito_items_color_vacio CHECK (color IS NULL OR color <> '');
CREATE INDEX IF NOT EXISTS idx_carrito_item_producto ON carrito_items (producto_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_carrito_item_producto_color ON carrito_items (carrito_id, producto_id, color) NULLS NOT DISTINCT;
CREATE INDEX IF NOT EXISTS idx_detalle_pedido ON detalle_pedidos (pedido_id);
CREATE INDEX IF NOT EXISTS idx_detalle_producto ON detalle_pedidos (producto_id);
CREATE INDEX IF NOT EXISTS idx_pago_estado ON pagos (estado);
CREATE INDEX IF NOT EXISTS idx_pago_pedido ON pagos (pedido_id);
CREATE INDEX IF NOT EXISTS ix_producto_colores_producto ON producto_colores (producto_id);
CREATE UNIQUE INDEX IF NOT EXISTS pk_producto_colores ON producto_colores (id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_producto_colores_nombre ON producto_colores (producto_id, nombre);
CREATE INDEX IF NOT EXISTS ix_ventas_local_sesion ON ventas_local (sesion_id);
CREATE UNIQUE INDEX IF NOT EXISTS pk_ventas_local ON ventas_local (id);
CREATE INDEX IF NOT EXISTS ix_items_producto ON venta_local_items (producto_id);
CREATE INDEX IF NOT EXISTS ix_items_venta ON venta_local_items (venta_id);
CREATE UNIQUE INDEX IF NOT EXISTS pk_venta_local_items ON venta_local_items (id);
