from gateway.infrastructure.oracle_pool import adquirir_conexion

_DDL_REFRESH_TOKENS = """
CREATE TABLE IF NOT EXISTS refresh_tokens (
   jti          VARCHAR2(36) PRIMARY KEY,
   user_id      VARCHAR2(36) NOT NULL,
   expira_en    TIMESTAMP NOT NULL,
   revocado     NUMBER(1) DEFAULT 0 NOT NULL,
   ip           VARCHAR2(45),
   user_agent   VARCHAR2(255),
   creado_en    TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""

_DDL_LOGS_SEGURIDAD = """
CREATE TABLE IF NOT EXISTS logs_seguridad (
   id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   evento     VARCHAR2(50) NOT NULL,
   user_id    VARCHAR2(36),
   ip         VARCHAR2(45),
   detalle    VARCHAR2(500),
   creado_en  TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""

def crear_tablas():
    with adquirir_conexion() as conexion:
        cursor = conexion.cursor()
        cursor.execute(_DDL_REFRESH_TOKENS )
        cursor.execute(_DDL_LOGS_SEGURIDAD)