"""DDL del gateway. Solo PostgreSQL.

El schema lo crea `migrations/postgres/schema_completo.sql`; esto queda como
red de seguridad idempotente para que el gateway no reviente al arrancar contra
una base vacia. Oracle usaba VARCHAR2 / NUMBER(1) / SYSTIMESTAMP y consultaba
`user_tab_columns`.
"""

from gateway.infrastructure.pg_pool import adquirir_conexion

_DDL_REFRESH_TOKENS = """
CREATE TABLE IF NOT EXISTS refresh_tokens (
   jti          varchar(36) PRIMARY KEY,
   user_id      varchar(36) NOT NULL,
   expira_en    timestamptz NOT NULL,
   revocado     boolean DEFAULT false NOT NULL,
   ip           varchar(45),
   user_agent   varchar(255),
   creado_en    timestamptz DEFAULT now()
)
"""

_DDL_LOGS_SEGURIDAD = """
CREATE TABLE IF NOT EXISTS logs_seguridad (
   id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   evento     varchar(50) NOT NULL,
   user_id    varchar(36),
   ip         varchar(45),
   detalle    varchar(500),
   creado_en  timestamptz DEFAULT now()
)
"""

_DDL_CODIGOS_VERIFICACION = """
CREATE TABLE IF NOT EXISTS codigos_verificacion (
   email       varchar(255) NOT NULL,
   codigo_hash varchar(255) NOT NULL,
   expira_en   timestamptz NOT NULL,
   usado       boolean DEFAULT false NOT NULL,
   creado_en   timestamptz DEFAULT now()
)
"""

_DDL_BLOQUEOS_LOGIN = """
CREATE TABLE IF NOT EXISTS bloqueos_login (
   id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   clave          varchar(255) NOT NULL,
   tipo           varchar(20) NOT NULL,
   fallos         integer DEFAULT 0 NOT NULL,
   nivel          integer DEFAULT 0 NOT NULL,
   bloqueo_hasta  timestamptz,
   creado_en      timestamptz DEFAULT now(),
   actualizado_en timestamptz DEFAULT now()
)
"""

# Soporte del ON CONFLICT que reemplaza al MERGE de Oracle. Ver el comentario en
# tools/migrar_ddl_oracle.py (INDICES_REQUERIDOS_POSTGRES).
_DDL_BLOQUEOS_LOGIN_UQ = """
CREATE UNIQUE INDEX IF NOT EXISTS bloqueos_login_clave_tipo_uq
ON bloqueos_login (lower(clave), tipo)
"""

_DDL_CODIGOS_RESPALDO = """
CREATE TABLE IF NOT EXISTS codigos_respaldo (
   id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id      varchar(36) NOT NULL,
   codigo_hash  varchar(255) NOT NULL,
   usado        boolean DEFAULT false NOT NULL,
   creado_en    timestamptz DEFAULT now()
)
"""

# Columnas nuevas sobre `usuarios` (ALTERs idempotentes).
_ALTERS_USUARIOS = [
    (
        "auth_provider",
        "ALTER TABLE usuarios ADD COLUMN auth_provider varchar(20) DEFAULT 'local' NOT NULL",
    ),
    (
        "google_sub",
        "ALTER TABLE usuarios ADD COLUMN google_sub varchar(255)",
    ),
    (
        "mfa_secret",
        "ALTER TABLE usuarios ADD COLUMN mfa_secret varchar(64)",
    ),
    (
        "mfa_activo",
        "ALTER TABLE usuarios ADD COLUMN mfa_activo boolean DEFAULT false NOT NULL",
    ),
]


def _columna_existe(conexion, tabla, columna):
    with conexion.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = current_schema() AND table_name = %s AND column_name = %s
            """,
            (tabla, columna),
        )
        return cursor.fetchone()[0] > 0


def crear_tablas():
    with adquirir_conexion() as conexion:
        with conexion.cursor() as cursor:
            for ddl in (
                _DDL_REFRESH_TOKENS,
                _DDL_LOGS_SEGURIDAD,
                _DDL_CODIGOS_VERIFICACION,
                _DDL_BLOQUEOS_LOGIN,
                _DDL_BLOQUEOS_LOGIN_UQ,
                _DDL_CODIGOS_RESPALDO,
            ):
                cursor.execute(ddl)

            for columna, alter in _ALTERS_USUARIOS:
                if not _columna_existe(conexion, "usuarios", columna):
                    cursor.execute(alter)