from gateway.infrastructure.oracle_pool import adquirir_conexion

_DDL_REFRESH_TOKENS = """
CREATE TABLE IF NOT EXISTS refresh_tokens (
   jti          VARCHAR2(36) PRIMARY KEY,
   user_id      VARCHAR2(36) NOT NULL,
   expira_en    TIMESTAMP NOT NULL,
   revocado     NUMBER(1) DEFAULT 0 NOT NULL,
   ip           VARCHAR2(45),
   user_agent   VARCHAR2(255),
   creado_en    TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""

_DDL_LOGS_SEGURIDAD = """
CREATE TABLE IF NOT EXISTS logs_seguridad (
   id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   evento     VARCHAR2(50) NOT NULL,
   user_id    VARCHAR2(36),
   ip         VARCHAR2(45),
   detalle    VARCHAR2(500),
   creado_en  TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""

_DDL_CODIGOS_VERIFICACION = """
CREATE TABLE IF NOT EXISTS codigos_verificacion (
   email       VARCHAR2(255) NOT NULL,
   codigo_hash VARCHAR2(255) NOT NULL,
   expira_en   TIMESTAMP NOT NULL,
   usado       NUMBER(1) DEFAULT 0 NOT NULL,
   creado_en   TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""

_DDL_BLOQUEOS_LOGIN = """
CREATE TABLE IF NOT EXISTS bloqueos_login (
   id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   clave          VARCHAR2(255) NOT NULL,
   tipo           VARCHAR2(20) NOT NULL,
   fallos         NUMBER DEFAULT 0 NOT NULL,
   nivel          NUMBER DEFAULT 0 NOT NULL,
   bloqueo_hasta  TIMESTAMP,
   creado_en      TIMESTAMP DEFAULT SYSTIMESTAMP,
   actualizado_en TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""

_DDL_CODIGOS_RESPALDO = """
CREATE TABLE IF NOT EXISTS codigos_respaldo (
   id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id      VARCHAR2(36) NOT NULL,
   codigo_hash  VARCHAR2(255) NOT NULL,
   usado        NUMBER(1) DEFAULT 0 NOT NULL,
   creado_en    TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""

# Columnas nuevas sobre `usuarios` (ALTERs idempotentes).
_ALTERS_USUARIOS = [
    (
        "auth_provider",
        "ALTER TABLE usuarios ADD auth_provider VARCHAR2(20) DEFAULT 'local' NOT NULL",
    ),
    (
        "google_sub",
        "ALTER TABLE usuarios ADD google_sub VARCHAR2(255)",
    ),
    (
        "mfa_secret",
        "ALTER TABLE usuarios ADD mfa_secret VARCHAR2(64)",
    ),
    (
        "mfa_activo",
        "ALTER TABLE usuarios ADD mfa_activo NUMBER(1) DEFAULT 0 NOT NULL",
    ),
]


def _columna_existe(conexion, tabla, columna):
    cursor = conexion.cursor()
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM user_tab_columns
        WHERE table_name = UPPER(:tabla) AND column_name = UPPER(:columna)
        """,
        tabla=tabla,
        columna=columna,
    )
    return cursor.fetchone()[0] > 0


def crear_tablas():
    with adquirir_conexion() as conexion:
        cursor = conexion.cursor()
        cursor.execute(_DDL_REFRESH_TOKENS)
        cursor.execute(_DDL_LOGS_SEGURIDAD)
        cursor.execute(_DDL_CODIGOS_VERIFICACION)
        cursor.execute(_DDL_BLOQUEOS_LOGIN)
        cursor.execute(_DDL_CODIGOS_RESPALDO)

        for columna, alter in _ALTERS_USUARIOS:
            if not _columna_existe(conexion, "usuarios", columna):
                cursor.execute(alter)