"""Convierte el DDL de Oracle (volcado con GET_DDL) a DDL de PostgreSQL.

Fuente de verdad: C:/Users/jonca/AppData/Local/Temp/opencode/ddl_oracle/ddl/*.sql
Salida: migrations/postgres/*.sql

Mapeo aplicado (ver design.md Decisión 5):
  RAW(16)              -> uuid              (DEFAULT SYS_GUID() -> gen_random_uuid())
  NUMBER(1,0)          -> boolean           (DEFAULT 1 -> true, DEFAULT 0 -> false)
  NUMBER(10,0)         -> integer
  NUMBER(19,0)         -> bigint
  NUMBER(p,s)          -> numeric(p,s)
  VARCHAR2(n)          -> varchar(n)
  TIMESTAMP(6) [WITH TIME ZONE] -> timestamptz
  DATE                 -> timestamptz  (excepcion en SOLO_FECHA, ver abajo)
  CLOB                 -> text
  BLOB                 -> bytea
  CURRENT_TIMESTAMP    -> now()

OJO con DATE: en Oracle es fecha + hora (7 bytes, hasta segundos), mientras que
`date` de Postgres solo guarda el dia. Mapearlo ahi no da error: Postgres acepta
`DATE` tal cual y trunca la hora en silencio. Por defecto va a `timestamptz` y
solo las columnas de SOLO_FECHA se quedan en `date`.
"""

import pathlib
import re

DUMP = pathlib.Path(r"C:\Users\jonca\AppData\Local\Temp\opencode\ddl_oracle")
OUT_DIR = pathlib.Path(r"C:\Users\jonca\ApoloVibes\migrations\postgres")

# Columnas DATE de Oracle que SI son fecha pura. Verificado contra los datos
# reales: SESIONES_VENTA.FECHA tiene 0 de 9 filas con hora distinta de
# 00:00:00, mientras que sus hermanas CREADO_EN/CERRADA_EN tienen 9 de 9.
# Cualquier DATE fuera de esta lista se traduce a timestamptz.
SOLO_FECHA = {
    "SESIONES_VENTA": {"FECHA"},
}
_SENTINEL = "__PG_DATE_PURO__"

# Las 20 tablas que se migran. Las otras 5 del schema son:
#   - *_BACKUP (4): respaldos de migraciones anteriores, no forman parte del modelo.
#   - DBTOOLS$EXECUTION_HISTORY: tabla interna de Oracle/SQL Developer.
EXCLUIDAS = {
    "CARRITO_ITEMS_BACKUP",
    "DETALLE_PEDIDOS_BACKUP",
    "PRODUCTOS_BACKUP",
    "VENTA_LOCAL_ITEMS_BACKUP",
    "DBTOOLS$EXECUTION_HISTORY",
}

# Indices sobre columna virtual de Oracle que si sabemos reproducir en Postgres.
# Clave: (tabla, indice). El unico que protege una regla de negocio va aqui.
INDICES_FUNCION_QUE_SE_EMITEN = {
    ("CARRITO_ITEMS", "UX_CARRITO_ITEM_PRODUCTO_COLOR"),
}


def quitar_balanceado(texto, patron_prefijo):
    """Elimina `<patron> (...)` incluyendo el grupo de parentesis balanceado."""
    while True:
        m = re.search(patron_prefijo, texto, flags=re.IGNORECASE)
        if not m:
            return texto
        j = texto.find("(", m.end())
        if j < 0:
            texto = texto[: m.start()] + " " + texto[m.end() :]
            continue
        depth, k = 0, j
        while k < len(texto):
            if texto[k] == "(":
                depth += 1
            elif texto[k] == ")":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        texto = texto[: m.start()] + " " + texto[k + 1 :]


def limpiar_fisico(sql):
    """Quita todo lo que es almacenamiento/segmentacion de Oracle.

    `USING INDEX` se acota hasta la coma o el cierre, nunca hasta el proximo
    parentesis: buscar el parentesis mas cercano se comia el CONSTRAINT ... FOREIGN KEY
    que Oracle emite cuando no hay STORAGE pegado al indice.
    """
    sql = re.sub(r"\bUSING\s+INDEX\b[^,]*?(?=\s*STORAGE\s*\()", " ", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bUSING\s+INDEX\b[^,]*?(?=,|\s*\))", " ", sql, flags=re.IGNORECASE)
    sql = quitar_balanceado(sql, r"\bSTORAGE\b")
    sql = quitar_balanceado(sql, r"\bLOB\b")
    sql = quitar_balanceado(sql, r"\bSTORE\s+AS\s+\w+")
    # Restos sueltos sin paresis.
    sql = re.sub(r"TABLESPACE\s+\"[^\"]*\"", "", sql)
    sql = re.sub(r"DEFAULT\s+COLLATION\s+\"[^\"]*\"", "", sql)
    sql = re.sub(r"\bENABLE\b", "", sql)
    sql = re.sub(r"\bDISABLE\b", "", sql)
    sql = re.sub(r"\bSEGMENT\s+CREATION\s+\w+", "", sql)
    sql = re.sub(r"\bPCT\w+\s+\d+", "", sql)
    sql = re.sub(r"\bINITRANS\s+\d+", "", sql)
    sql = re.sub(r"\bMAXTRANS\s+\d+", "", sql)
    sql = re.sub(r"\bNOCOMPRESS\b|\bCOMPRESS\b|\bLOGGING\b|\bNOCACHE\b", "", sql)
    sql = re.sub(r"\bKEEP_DUPLICATES\b", "", sql)
    sql = re.sub(r"IN\s+ROW\s+\d+|\bCHUNK\s+\d+", "", sql)
    return sql


IDENTITY_OPTS = re.compile(
    r"\bGENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY\s+"
    r"(?:MINVALUE\s+\S+\s+)?"
    r"(?:MAXVALUE\s+\S+\s+)?"
    r"(?:INCREMENT\s+BY\s+(\d+)\s+)?"
    r"(?:START\s+WITH\s+(\d+)\s+)?"
    r"(?:CACHE\s+\d+\s+)?"
    r"(?:NOORDER\s+|ORDER\s+|NOCYCLE\s+|NOKEEP\s+|NOSCALE\s+)*",
    re.IGNORECASE,
)


def _identity_pg(m):
    """La sintaxis de identity de Oracle no existe en Postgres: se reduce a START/INCREMENT."""
    incr = m.group(1) or "1"
    start = m.group(2) or "1"
    return f"GENERATED BY DEFAULT AS IDENTITY (START WITH {start} INCREMENT BY {incr}) "


def mapear_tipos(sql, tabla=None):
    # Identity primero: sus opciones de Oracle hay que traducirlas antes de que
    # las reglas de NUMBER leselsen encima.
    sql = IDENTITY_OPTS.sub(_identity_pg, sql)
    # Un NUMBER sin precision delante de IDENTITY es una secuencia entera.
    sql = re.sub(
        r"\bNUMBER\b(?=\s+GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY)",
        "bigint",
        sql,
        flags=re.IGNORECASE,
    )

    # Los NUMBER(1,0) son booleanos: hay que resolverlos antes que el resto
    # de NUMBER porque 'NUMBER(1,0)' matchearia el patron generico.
    sql = re.sub(r"NUMBER\(1,\s*0\)\s+DEFAULT\s+1", "boolean DEFAULT true", sql)
    sql = re.sub(r"NUMBER\(1,\s*0\)\s+DEFAULT\s+0", "boolean DEFAULT false", sql)
    sql = re.sub(r"NUMBER\(1,\s*0\)", "boolean", sql)

    sql = re.sub(r"RAW\(\s*16\s*\)", "uuid", sql)
    sql = re.sub(r"SYS_GUID\(\)", "gen_random_uuid()", sql)
    sql = re.sub(r"NUMBER\(\s*19\s*,\s*0\s*\)", "bigint", sql)
    sql = re.sub(r"NUMBER\(\s*10\s*,\s*0\s*\)", "integer", sql)
    sql = re.sub(r"NUMBER\(\s*10\s*,\s*2\s*\)", "numeric(10,2)", sql)
    sql = re.sub(r"NUMBER\(\s*\d+\s*,\s*\d+\s*\)", "numeric", sql)
    sql = re.sub(r"\bNUMBER\b(?!\s*\()", "numeric", sql)
    sql = re.sub(r"VARCHAR2\(", "varchar(", sql, flags=re.IGNORECASE)
    # VARCHAR2(n CHAR) declara longitud en caracteres; Postgres no tiene esa
    # unidad y `varchar(150 CHAR)` es error de sintaxis. Se descarta.
    sql = re.sub(r"(\b(?:var)?char\(\s*\d+)\s+CHAR\s*\)", r"\1)", sql, flags=re.IGNORECASE)
    sql = re.sub(r"NVARCHAR2\(", "varchar(", sql, flags=re.IGNORECASE)
    sql = re.sub(r"CHARACTER\s+VARYING\(", "varchar(", sql, flags=re.IGNORECASE)
    sql = re.sub(r"CLOB\b", "text", sql)
    sql = re.sub(r"BLOB\b", "bytea", sql, flags=re.IGNORECASE)

    # Orden critico: primero las funciones de Oracle, despues los tipos.
    # Un patron TIMESTAMP sin \b matchea dentro de CURRENT_TIMESTAMP y lo destruye.
    sql = re.sub(r"\bCURRENT_TIMESTAMP(\s*\(\s*\d+\s*\))?", "now()", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bSYSTIMESTAMP\b", "now()", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bSYSDATE\b", "now()", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bTIMESTAMP\s*\(\s*\d+\s*\)\s*WITH\s+TIME\s+ZONE\b", "timestamptz", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bTIMESTAMP\s*\(\s*\d+\s*\)", "timestamptz", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bTIMESTAMP\s+WITH\s+TIME\s+ZONE\b", "timestamptz", sql, flags=re.IGNORECASE)

    # Oracle DATE lleva fecha Y hora. `date` de Postgres no tiene hora, asi que
    # dejarla pasar tal cual trunca la hora sin dar ningun error. Se protegen con
    # un sentinel las columnas de SOLO_FECHA y el resto pasa a timestamptz.
    solo = SOLO_FECHA.get((tabla or "").upper(), set())
    for col in solo:
        # El DDL de Oracle trae los identificadores entrecomillados ("FECHA" DATE)
        # y las comillas se quitan despues, en limpiar_tabla. La opcional "? "
        # cubre las dos formas.
        sql = re.sub(
            rf'\b({re.escape(col)}"?\s+)DATE\b',
            rf'\1{_SENTINEL}',
            sql,
            flags=re.IGNORECASE,
        )
    # El lookbehind evita partir CURRENT_DATE; el lookahead evita comerse el
    # DATE de un identificador usado como prefijo de otro.
    sql = re.sub(r"(?<![\w])DATE(?!\s*\()", "timestamptz", sql, flags=re.IGNORECASE)
    sql = sql.replace(_SENTINEL, "date")

    sql = re.sub(r'"ADMIN"\s*\.\s*', "", sql)
    sql = re.sub(r'COLLATE\s+"USING_NLS_COMP"', "", sql)
    return sql


def limpiar_tabla(sql):
    # Quita el punto y coma final y el nombre cualificado en el CREATE.
    sql = re.sub(r"CREATE\s+TABLE\s+[\w$]*\.?\s*", "CREATE TABLE ", sql, flags=re.IGNORECASE)
    # Oracle entrega los identificadores entrecomillados en mayusculas ("ROL"). En
    # Postgres eso crea una columna llamada ROL, distinta del `rol` sin comillas que
    # usan los CHECK y el SQL crudo de los repositorios. Se Bajan a minusculas.
    sql = sql.replace('"', "")
    return sql.strip().rstrip(";").strip()


def leer_indices_expresion():
    """Indices con expresion (columna virtual SYS_NCxxx$ en Oracle).

    Viven en user_ind_expressions: GET_DDL no las expone.
    Devuelve [(tabla, indice, unico, expresion_oracle)].
    """
    ruta = DUMP / "constraints" / "index_expressions.txt"
    if not ruta.exists():
        return []
    salida = []
    for linea in ruta.read_text(encoding="utf-8").splitlines()[1:]:
        p = linea.split("|", 3)
        if len(p) < 4:
            continue
        salida.append((p[0].strip(), p[1].strip(), p[2].strip() == "UNIQUE", p[3].strip()))
    return salida


def traducir_indice_expresion(expresion, es_unico):
    """Traduce la expresion de un indice Oracle a Postgres.

    Devuelve (columnas, nulls_not_distinct). Levanta si no reconoce la expresion:
    es preferible no generar el indice a inventar una equivalencia falsa.
    """
    e = " ".join(expresion.split())

    m = re.match(r'^SYS_EXTRACT_UTC\(\s*"?([A-Za-z0-9_$]+)"?\s*\)$', e, re.IGNORECASE)
    if m:
        # Oracle no normaliza TIMESTAMP WITH TIME ZONE a UTC, por eso necesita
        # SYS_EXTRACT_UTC para ordenar. Postgres guarda timestamptz ya en UTC:
        # un indice plano sobre la columna ordena exactamente igual.
        return [m.group(1).lower()], False

    m = re.match(r'^NVL\(\s*"?([A-Za-z0-9_$]+)"?\s*,\s*\'[^\']*\'\s*\)$', e, re.IGNORECASE)
    if m:
        col = m.group(1).lower()
        # En un indice UNIQUE, Oracle trata el NULL como igual a ' ' por el NVL.
        # Postgres lo reproduce con NULLS NOT DISTINCT sobre la columna.
        return [col], True if es_unico else False

    m = re.match(r'^LOWER\(\s*"?([A-Za-z0-9_$]+)"?\s*\)$', e, re.IGNORECASE)
    if m:
        return [f"lower({m.group(1).lower()})"], False

    raise ValueError(f"expresion de indice sin traduccion conocida: {expresion!r}")


def leer_indices():
    """Devuelve {tabla: {idx: {unique, cols}}} ya sin los indices redundantes.

    Se descartan losIndices que solo respaldan la PK o una constraint UNIQUE:
    en Oracle existen como objeto propio, pero en Postgres los crea la propia
    constraint y emitirlos seria duplicarlos.
    """
    ruta = DUMP / "constraints" / "indexes.txt"
    if not ruta.exists():
        return {}

    unicos_por_tabla = set()
    ruta_c = DUMP / "constraints" / "constraints.txt"
    if ruta_c.exists():
        for linea in ruta_c.read_text(encoding="utf-8").splitlines()[1:]:
            partes = linea.split("|")
            if len(partes) >= 3 and partes[2].strip() == "U":
                unicos_por_tabla.add((partes[0].strip(), partes[1].strip()))

    acc = {}
    for linea in ruta.read_text(encoding="utf-8").splitlines()[1:]:
        partes = linea.split("|")
        if len(partes) < 5:
            continue
        tabla, idx, unico, col, _pos = (p.strip() for p in partes[:5])
        if idx.startswith("SYS_"):
            continue
        if (tabla, idx) in unicos_por_tabla:
            continue
        acc.setdefault(tabla, {}).setdefault(idx, {"unique": unico == "UNIQUE", "cols": []})
        acc[tabla][idx]["cols"].append(col)
    return acc


def leer_fks():
    """Devuelve [(padre, hijo)] leyendo las FK de Oracle.

    Una FK se identifica por constraint_type 'R'; el padre es la tabla que
    posee la constraint referenciada (r_constraint_name).
    """
    ruta = DUMP / "constraints" / "constraints.txt"
    if not ruta.exists():
        return []
    filas = ruta.read_text(encoding="utf-8").splitlines()[1:]
    duenio = {}
    refs = []
    for linea in filas:
        p = linea.split("|")
        if len(p) < 6:
            continue
        tabla, cons, tipo, _st, _chk, rcons = (x.strip() for x in p[:6])
        duenio[cons] = tabla
        if tipo == "R" and rcons:
            refs.append((tabla, rcons))
    pares = []
    for hijo, rcons in refs:
        padre = duenio.get(rcons)
        if padre and padre != hijo:
            pares.append((padre, hijo))
    return pares


def orden_dependencias(tablas, pares):
    """Ordena por dependencias de FK. Si hay ciclo, emite el resto alfabeticamente."""
    import collections

    padres = {t: set() for t in tablas}
    for padre, hijo in pares:
        if padre in padres and hijo in padres:
            padres[hijo].add(padre)
    orden, hechos = [], set()
    pendientes = set(tablas)
    while pendientes:
        listos = sorted(t for t in pendientes if not (padres[t] - hechos))
        if not listos:
            # Ciclo (FK autoinreferencial): no se puede ordenar, se emite igual.
            for t in sorted(pendientes):
                orden.append(t)
            break
        for t in listos:
            orden.append(t)
            hechos.add(t)
            pendientes.discard(t)
    return orden


# Indices que Postgres necesita y Oracle no tiene. No derivan del origen: son el
# soporte del `ON CONFLICT` que reemplaza al `MERGE` de Oracle en el gateway.
# El indice es UNIQUE sobre (lower(clave), tipo) para preservar la semántica
# case-insensitive del predicado original.
INDICES_REQUERIDOS_POSTGRES = {
    "BLOQUEOS_LOGIN": [
        "CREATE UNIQUE INDEX IF NOT EXISTS bloqueos_login_clave_tipo_uq "
        "ON bloqueos_login (lower(clave), tipo);",
    ],
}


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ddl_dir = DUMP / "ddl"
    indices = leer_indices()

    tablas_sql = {}
    generadas = []
    pendientes = []
    # indice -> expresion Oracle (un indice con varias columnas virtuales no existe hoy)
    expresiones = {}
    for _t, idx, _u, expr in leer_indices_expresion():
        if idx in expresiones:
            raise ValueError(f"el indice {idx} tiene mas de una columna virtual: resolver a mano")
        expresiones[idx] = expr
    for f in sorted(ddl_dir.glob("*.sql")):
        tabla = f.stem
        if tabla in EXCLUIDAS:
            print(f"  - {tabla}: EXCLUIDA")
            continue

        crudo = f.read_text(encoding="utf-8")
        sql = limpiar_tabla(mapear_tipos(limpiar_fisico(crudo), tabla))

        cabecera = (
            f"-- {tabla}: generado desde el DDL de Oracle (DBMS_METADATA.GET_DDL).\n"
            f"-- No editar a mano: regenerar con tools/migrar_ddl_oracle.py.\n\n"
        )

        extras = []
        for idx, info in sorted(indices.get(tabla, {}).items()):
            if not info["cols"]:
                continue

            # Las columnas SYS_NCxxx$ son virtuales de Oracle: se sustituyen por la
            # expresion traducida EN SU POSICION. Reemplazar el indice entero por la
            # expresion perderia el resto de las columnas del indice compuesto.
            cols, nnd, fallo = [], False, None
            for c in info["cols"]:
                c = c.strip()
                if re.match(r"^SYS_NC\d+\$$", c, re.IGNORECASE):
                    expr = expresiones.get(idx)
                    if not expr:
                        fallo = f"columna virtual {c} sin expresion en user_ind_expressions"
                        break
                    try:
                        sub, n = traducir_indice_expresion(expr, info["unique"])
                    except ValueError as e:
                        fallo = str(e)
                        break
                    cols.extend(sub)
                    nnd = nnd or n
                else:
                    cols.append(c.lower())

            if fallo:
                pendientes.append((tabla, idx, list(info["cols"]), info["unique"]))
                print(f"  ! {tabla}.{idx}: {fallo}")
                continue

            sufijo = " NULLS NOT DISTINCT" if nnd else ""
            extras.append(
                f'CREATE {"UNIQUE " if info["unique"] else ""}INDEX IF NOT EXISTS '
                f'{idx.lower()} ON {tabla.lower()} ({", ".join(cols)}){sufijo};'
            )
            if nnd or any("$" in x.upper() for x in info["cols"]):
                print(f"  ~ {tabla}.{idx}: -> ({', '.join(cols)}){sufijo}")

        # CHECK que Postgres necesita y Oracle no: alli '' y NULL son distintos
        # para un indice unico sobre color, y el dominio no admite la cadena vacia.
        if tabla == "CARRITO_ITEMS":
            extras.insert(
                0,
                "ALTER TABLE carrito_items ADD CONSTRAINT ck_carrito_items_color_vacio "
                "CHECK (color IS NULL OR color <> '');",
            )

        # Indices que Postgres EXIGE y Oracle no tenia. No son una copia del
        # origen: son el soporte del `ON CONFLICT` que reemplaza al `MERGE`.
        # El MERGE de Oracle hace upsert por PREDICADO (LOWER(clave)=LOWER(...)),
        # sin garantia de unicidad: dos logins fallando en paralelo por la misma
        # clave insertaban dos filas y el MERGE matcheaba varias (ORA-30926).
        # El indice unique sobre (lower(clave), tipo) cierra esa carrera y es
        # justo lo que `ON CONFLICT (lower(clave), tipo)` necesita para existir.
        extras.extend(INDICES_REQUERIDOS_POSTGRES.get(tabla, []))

        cuerpo = cabecera + sql + ";\n"
        if extras:
            cuerpo += "\n" + "\n".join(extras) + "\n"
        (OUT_DIR / f"{tabla.lower()}.sql").write_text(cuerpo, encoding="utf-8")

        tablas_sql[tabla] = (sql, extras)
        generadas.append(tabla)
        print(f"  + {tabla} -> {tabla.lower()}.sql")

    # Schema combinado en orden de dependencias: es lo que se aplica.
    orden = orden_dependencias(generadas, leer_fks())
    partes = [
        "-- Schema Postgres de ApoloVibes, generado desde el DDL de Oracle APOLODEV.",
        "-- Ordenado por dependencias de FK. Regenerar con tools/migrar_ddl_oracle.py.",
        "",
    ]
    for t in orden:
        partes.append(f"-- ---- {t}")
        partes.append(tablas_sql[t][0] + ";")
        partes.append("")
    todos_idx = [i for t in orden for i in tablas_sql[t][1]]
    if todos_idx:
        partes.append("-- ---- Indices")
        partes.extend(todos_idx)
    (OUT_DIR / "schema_completo.sql").write_text("\n".join(partes) + "\n", encoding="utf-8")

    print(f"\nTOTAL GENERADAS: {len(generadas)}")
    if pendientes:
        print(f"\nINDICES PENDIENTES ({len(pendientes)}) -- sobre columna virtual de Oracle:")
        for tabla, idx, cols, unico in pendientes:
            marca = "UNIQUE " if unico else ""
            print(f"  ! {marca}{tabla}.{idx} -> {', '.join(cols)}")
        print("  Requieren user_ind_expressions para traducir la expresion.")
    print("orden:", " -> ".join(orden))
    print("schema combinado: migrations/postgres/schema_completo.sql")


if __name__ == "__main__":
    main()